# Generated by Django 5.1.7 on 2025-04-02 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_document_title_cart_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='department',
            field=models.CharField(default='Unknown', max_length=250),
        ),
    ]
