# Generated by Django 5.2 on 2025-04-15 05:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_document_title_cart_document_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UseProfile',
            new_name='UserProfile',
        ),
    ]
