# Generated by Django 5.1.7 on 2025-04-02 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_document_department'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='department',
            new_name='region',
        ),
    ]
