# Generated by Django 5.2 on 2025-04-15 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_useprofile_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='abc',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
    ]
