# Generated by Django 5.2 on 2025-05-15 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_userprofile_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='category',
            field=models.CharField(blank=True, choices=[('drainage_fee', 'Drainage Fee'), ('equipment_rental', 'Equipment Rental'), ('filling_fee_certification', 'Filling Fee/Certification'), ('inspection_fee', 'Inspection Fee'), ('irrigation_services_fee', 'Irrigation Services Fee'), ('scraped_fix_assets', 'Scraped Fix Assets'), ('verification_authentication', 'Verification and Authentication'), ('bidding_documents', 'Bidding Documents'), ('finance', 'Finance')], max_length=50),
        ),
    ]
