# Generated by Django 5.2 on 2025-04-30 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_bid_bidding_end_date_bid_bidding_start_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='bidding_end_date',
        ),
        migrations.RemoveField(
            model_name='bid',
            name='bidding_start_date',
        ),
        migrations.RemoveField(
            model_name='bid',
            name='status',
        ),
        migrations.AddField(
            model_name='document',
            name='bidding_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='bidding_start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('awarded', 'Awarded')], default='open', max_length=20),
        ),
    ]
