# Generated by Django 5.2 on 2025-05-20 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_userprofile_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='category',
            field=models.CharField(blank=True, choices=[('equipment_rental', 'Equipment Rental'), ('bidding_documents', 'Bidding Documents'), ('finance', 'Finance')], max_length=50),
        ),
    ]
