# Generated by Django 5.2 on 2025-05-02 02:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_bid_bidding_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('under_review', 'Under Review'), ('rejected', 'Rejected')], default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
