# Generated by Django 5.2 on 2025-04-14 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='custom_order_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
