# Generated by Django 5.2 on 2025-05-05 05:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_bid_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('under_review', 'Under Review'), ('rejected', 'Rejected')], default='pending', max_length=50),
        ),
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('email_add', models.CharField(max_length=255)),
                ('number', models.IntegerField(null=True)),
                ('invoice_number', models.CharField(max_length=100, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending Verification'), ('paid', 'Paid'), ('unpaid', 'Unpaid')], default='pending', max_length=50)),
                ('issued_date', models.DateField(default=django.utils.timezone.now)),
                ('bid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='billing', to='core.bid')),
            ],
        ),
    ]
