# Generated by Django 5.2 on 2025-05-05 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_bid_status_billing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='number',
            field=models.IntegerField(max_length=55, null=True),
        ),
    ]
