# Generated by Django 5.2 on 2025-05-05 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_billing_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='number',
            field=models.BigIntegerField(null=True),
        ),
    ]
