# Generated by Django 5.2 on 2025-05-05 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_billing_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billing',
            name='payment_date',
        ),
    ]
