# Generated by Django 5.2 on 2025-05-05 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_billing_payment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('under_review', 'Under Review'), ('rejected', 'Rejected'), ('paid', 'Paid')], default='pending', max_length=50),
        ),
    ]
