# Generated by Django 5.2 on 2025-04-25 00:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('asset_tag', models.CharField(max_length=50, unique=True)),
                ('category', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='documents/')),
                ('status', models.CharField(choices=[('available', 'Available'), ('maintenance', 'Maintenance'), ('retired', 'Retired')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RentalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_by', models.CharField(max_length=255)),
                ('purpose', models.TextField()),
                ('rental_start_date', models.DateField()),
                ('rental_end_date', models.DateField()),
                ('actual_return_date', models.DateField(blank=True, null=True)),
                ('no_of_days_hours', models.CharField(max_length=100)),
                ('rental_rate', models.IntegerField()),
                ('total_rent_cost', models.IntegerField(default=0)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('billed', 'Billed'), ('paid', 'Paid'), ('waived', 'Waived')], default='pending', max_length=20)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('returned', 'Returned')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_requests', to='equipment.equipment')),
            ],
        ),
    ]
