# Generated by Django 5.2 on 2025-05-09 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalrequest',
            name='requested_by',
            field=models.CharField(max_length=255),
        ),
    ]
