# Generated by Django 5.2 on 2025-04-25 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='rental_price',
            field=models.IntegerField(default=344),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='equipment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='equipments/'),
        ),
    ]
