# Generated by Django 5.2 on 2025-04-25 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_equipment_rental_price_alter_equipment_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='category',
        ),
    ]
