# Generated by Django 5.2 on 2025-05-23 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0003_alter_rentalrequest_requested_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalrequest',
            name='invoice_number',
            field=models.CharField(default=2323, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
