# Generated by Django 5.2 on 2025-04-25 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0003_remove_equipment_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='rental_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
