# Generated by Django 5.2 on 2025-04-28 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0004_equipment_rental_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='asset_tag',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
