# Generated by Django 5.2 on 2025-04-28 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0005_alter_equipment_asset_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='rental_price',
            field=models.IntegerField(null=True),
        ),
    ]
